export const types = {
    // Action only for saga worker
    FETCH_POSTS: "FETCH_POSTS",
    LIKE_POST_WORKER: "LIKE_POST_WORKER",
    UNLIKE_POST_WORKER: "UNLIKE_POST_WORKER",

    START_FETCHING_POSTS: "START_FETCHING_POSTS",
    STOP_FETCHING_POSTS: "STOP_FETCHING_POSTS",
    FILL_POSTS:  "FILL_POSTS",
    FILL_USERS: "FILL_USERS",

    LIKE_POST:   "LIKE_POST",
    UNLIKE_POST: "UNLIKE_POST",

    EMIT_ERROR_POSTS: "EMIT_ERROR_POSTS",
    SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
};
