export const types = {
  // Action only for saga worker
  AUTHENTICATE: "AUTHENTICATE",

  START_FETCHING_AUTH: "START_FETCHING_AUTH",
  STOP_FETCHING_AUTH: "STOP_FETCHING_AUTH",
  FILL_PROFILE: "FILL_PROFILE",
  LOG_OUT: "LOG_OUT",
  EMIT_ERROR_AUTH: "EMIT_ERROR_AUTH",
  CLEAR_ERROR: "CLEAR_ERROR",
};
